spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/nbanews}
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://postgresql:5432/nbanews
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 100
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.gmail.com
    port: 587
    username: nb4news@gmail.com
    password: tvydgzdkbzvuqpzy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  liquibase:
    enabled: true
server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false
    include-stacktrace: on_param