spring:
  datasource:
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/nbanews
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: egor.ershofff@gmail.com
    password: jcrnokhpzkkrcuwm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true