create table news_source
(
    id    int8 generated by default as identity,
    image varchar      not null,
    name  varchar(255) not null unique,
    primary key (id)
);

CREATE TABLE news
(
    id             int8 generated by default as identity,
    content_author  varchar(50),
    image_url       varchar,
    news_date      date not null,
    news_time      time not null,
    source         varchar(255),
    subhead        varchar(255),
    title          varchar(255),
    news_source_id int8 not null,
    primary key (id),
    constraint FK_news_source_news foreign key (news_source_id) references news_source
);

CREATE TABLE users
(
    id       int8 generated by default as identity,
    avatar   varchar,
    email    varchar(50),
    enabled  boolean not null,
    locked   boolean not null,
    nickname varchar(50),
    password varchar(255),
    primary key (id),
    constraint uk_email_nickname unique (email, nickname)
);

CREATE TABLE user_role
(
    user_id int8 not null,
    role    varchar(15),
    constraint uk_user_roles unique (user_id, role),
    CONSTRAINT FK_user_user_role FOREIGN KEY (user_id) references users on delete cascade
);

CREATE TABLE comment
(
    id        int8 generated by default as identity,
    comment   varchar(512),
    date_time timestamp not null,
    news_id   int8      not null,
    user_id   int8      not null,
    primary key (id),
    CONSTRAINT FK_news_comment FOREIGN KEY (news_id) references news on delete cascade,
    CONSTRAINT FK_user_comment FOREIGN KEY (user_id) references users on delete cascade
);

CREATE TABLE like_dislike
(
    id        int8 generated by default as identity,
    like_type int4 not null,
    news_id   int8 not null,
    user_id   int8 not null,
    primary key (id),
    CONSTRAINT FK_news_like_dislike FOREIGN KEY (news_id) references news on delete cascade,
    CONSTRAINT FK_user_like_dislike FOREIGN KEY (user_id) references users on delete cascade
);

CREATE TABLE confirmation_token
(
    id           int8 generated by default as identity,
    confirmed_at timestamp,
    created_at   timestamp    not null,
    expires_at   timestamp    not null,
    token        varchar(255) not null,
    user_id      int8         not null,
    primary key (id),
    CONSTRAINT FK_user_token FOREIGN KEY (user_id) references users on delete cascade
);